config/routes.rb
Rails.application.routes.draw do
  resources :arguments do
    resources :events do
      resources :reactions
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "arguments#index"
end

app/models/argument.rb
class Argument

  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :name, type: String, required: true
  has_many :events, dependent: :destroy
end

app/models/event.rb
class Event
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :body, :type => Text
  field :position, :type => Integer
  belongs_to :argument
  has_many :reaction, dependent: :destroy 
end

app/models/reaction.rb
class Reaction
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :body, :type => Text
  field :position, :type => Integer
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User
  include NoBrainer::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time
  include NoBrainer::Document::Timestamps

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  use_growlyflash
end

app/controllers/arguments_controller.rb
class ArgumentsController < ApplicationController
  # before_action :set_argument, only: [:show, :edit, :update, :destroy]
  require "responders/nobrainer_sse_responder"

  responders :nobrainer_sse
  respond_to :html, :sse, only: [:index]
  respond_to :json, only: [:create]

  # GET /arguments
  def index
    arguments = Argument.all
    respond_with arguments
  end

  # POST /arguments
  def create
    argument = Argument.create! argument_params
    MakeArgument.new(argument.id).enqueue
    redirect_to arguments_path
  end

  # GET /arguments/1
  def show
  end

  # GET /arguments/new
  def new
    @argument = Argument.new
  end

  # GET /arguments/1/edit
  def edit
  end

  # PATCH/PUT /arguments/1
  def update
    if @argument.update(argument_params)
      flash[:notice] = "Argument was successfuly updated."
    else
      flash[:alert] = "There was an error saving the argument. Please try again."
    end
  end

  # DELETE /arguments/1
  def destroy
    if @argument.destroy
      flash[:notice] = "Argument was successfully deleted."
    else
      flash[:alert] = "There was an error deleting the argument. Please try again."
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_argument
    @argument = Argument.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def argument_params
    params.require(:argument).permit(:body)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  require "responders/nobrainer_sse_responder"

  responders :nobrainer_sse
  respond_to :html, :sse, only: [:index]
  respond_to :json, only: [:create]

  # GET /arguments/1/events
  def index
    events = Argument.find(params[:argument_id]).events || {}
    respond_with events
  end

  # POST /arguments/1/events/
  def create
    if Event.create!(event_params)
      flash[:notice] = "Event was saved."
    else
      flash.now[:alert] = "There was an error saving the event. Please try again."
    end
  end

  # GET /arguments/1/events/7
  def show
  end

  # GET /arguments/1/events/new
  def new
    @event = Event.new
  end

  # GET /arguments/1/events/7/edit
  def edit
  end

  # PATCH/PUT /arguments/1/events/7
  def update
    if @event.update(event_params)
      flash[:notice] = "Event was successfuly updated."
    else
      flash[:alert] = "There was an error saving the event. Please try again."
    end
  end

  # DELETE /arguments/:argument_id/events/1
  def destroy
    if @event.destroy
      flash[:notice] = "Event was successfully deleted."
    else
      flash[:alert] = "There was an error deleting the event. Please try again."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit([:argument_id, :body, :position])
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :set_reaction, only: [:show, :edit, :update, :destroy]
  require "responders/nobrainer_sse_responder"

  responders :nobrainer_sse
  respond_to :html, :sse, only: [:index]
  respond_to :json, only: [:create]

  def index
    reactions = Event.find(params[:event_id]).reaction || {}
    respond_with reactions
  end

  # POST /arguments/1/events/7/reactions
  def create
    Reaction.create!(reaction_params)
  end

  # GET /arguments/1/events/7/reactions/99
  def show
  end

  # GET /arguments/1/events/7/reactions/new
  def new
    @reaction = Reaction.new
  end

  # GET /arguments/1/events/7/reactions/99/edit
  def edit
  end

  # PATCH/PUT /arguments/1/events/7/reactions/99
  def update
    if @reaction.update(event_params)
      flash[:notice] = "Reaction was successfuly updated."
    else
      flash[:alert] = "There was an error saving the reaction. Please try again."
    end
  end

  # DELETE /arguments/1/events/7/reactions/99
  def destroy
    if @reaction.destroy
      flash[:notice] = "Reaction was successfully deleted."
    else
      flash[:alert] = "There was an error deleting the reaction. Please try again."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reaction
      @reaction = Reaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reaction_params
      params.require(:reaction).permit([:body, :user_id, :event_id, :position])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arguments_helper.rb
module ArgumentsHelper
end

app/views/arguments/_form.html.erb
<%= form_with(model: argument, local: true) do |form| %>
  <% if argument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(argument.errors.count, "error") %> prohibited this argument from being saved:</h2>

      <ul>
      <% argument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/arguments/edit.html.erb
<h1>Editing Argument</h1>

<%= render 'form', argument: @argument %>

<%= link_to 'Show', @argument %> |
<%= link_to 'Back', arguments_path %>

app/views/arguments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arguments</h1>


<p><%= arguments_url(format: :sse) %></p>
  <%= react_component("ArgumentContainer", url: arguments_url(format: :sse)) %>

<br>

<%= link_to 'New Argument', new_argument_path %>

app/views/arguments/new.html.erb
<h1>New Argument</h1>

<%= render 'form', argument: @argument %>

<%= link_to 'Back', arguments_path %>

app/views/arguments/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong><%= @argument.name %></strong>
</h1>

<%= react_component("ArgumentContainer", {url: arguments_path({format: :sse}) %>

<%= link_to 'Edit', edit_argument_path(@argument) %> |
<%= link_to 'Back', arguments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DebateNobrainer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

  </head>

  <body>
    <%= yield %>
  </body>
</html>